### ISSUE TITLE
Enable date before today

### ISSUE THREAD

**Issue by sqall01** [raymondborkowski/tiny-picker#2]
Hi,

I am just testing out your package. I am not the biggest JavaScript programmer, but I have to say it is fairly easy to use. Thanks for this.

In my project I have to be able to select dates that are before today. However, these dates are disabled and not selectable. I have tried to get them selectable, but was not successful so far (as I said, not the biggest JavaScript programmer). Can you help me here? Is there an undocumented option for this? Can you point me in the right direction?

Thanks,
sqall

**Comment by raymondborkowski** [comment]
Hi @sqall01, I did not have that feature before but I just added it:
https://github.com/raymondborkowski/tiny-picker/pull/3

When you set the options you want for the `TinyPicker` you can add 

`allowPast: true`

just make sure you update your package to version 2.1.0

**Comment by sqall01** [comment]
Thank you very much. I will check it out as soon as time allows it :)
